### ISSUE TITLE
Error message about undefined property cutofftime

### ISSUE THREAD

**Issue by DavidPruem** [Panopto/moodle-mod_panoptosubmission#18]
After update to v2022122000 I get the following error:
**`Notice: Undefined property: stdClass::$cutofftime in /mod/panoptosubmission/locallib.php on line 60`**

Possibly related to the missing CFG error in the Panopto for Moodle Block (https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/issues/194)

**Comment by jmalmsten-panopto** [comment]
Hi,

Thank you for bringing this issue to our attention. I think I see the issue and I have filed an internal work item to fix this issue. 

Thanks,
Joe

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be resolved with the latest release. 

Thanks,
Joe
