### ISSUE TITLE
Moodle plugin not hosted on the Moodle plugins directory

### ISSUE THREAD

**Issue by ZadkielSantospirito** [Panopto/moodle-mod_panoptosubmission#2]
This plugin is currently not in the Moodle plugins directory - can you tell me when this is intended to be changed?

**Comment by jmalmsten-panopto** [comment]
Hi,

We are currently in the process of getting this plug-in approved by Moodle.org.

Thank you for your patience,
Joe

**Comment by jmalmsten-panopto** [comment]
Hi,

The student submission plugin should now be hosted on moodle.org plugins directory. 

Thanks,
Joe
