### ISSUE TITLE
plugin disables RTC options within moodle atto editor

### ISSUE THREAD

**Issue by SYoung3000** [Panopto/moodle-mod_panoptosubmission#21]
In the atto editor on the grade screen for a panopto submission, the RTC options to add video or audio (core features) to the text area are missing - it seems exclusive to this plugin and doesn't throw any useful console errors or log errors when this occurs

**Comment by zeroAps** [comment]
I have added internal work item to add this in the future, since current plugin doesn't support this.

Thanks,
-Adis

**Comment by zeroAps** [comment]
We have added options to add RTC video or audio with the latest plugin as teacher feedback with the latest released version of the plugin. Closing this for now.
